# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-shout"
  s.version = "2.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Jennings", "Niko Dittmann"]
  s.date = "2012-12-09"
  s.description = "Ruby bindings for libshout 2, a \"Library which can be used to write a source client like ices\" for Icecast (http://www.icecast.org/download.php)."
  s.email = "mail@niko-dittmann.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "VERSION",
    "ext/extconf.rb",
    "ext/shout_ext.c",
    "lib/shout.rb"
  ]
  s.homepage = "http://github.com/niko/ruby-shout"
  s.require_paths = ["lib"]
  s.rubyforge_project = "ruby-shout"
  s.rubygems_version = "1.8.10"
  s.summary = "Send audio over the network to an Icecast server"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

